name = "shopper-ai-manager"
main = "worker.js"
compatibility_date = "2026-09-26"

[vars]
WEBSITE_URL = "https://shopperssuggestions.online"

[[d1_databases]]
binding = "DB"
database_name = "product-db"
database_id = "7fc3ac99-20b3-40f1-a022-1a11a0b4a177"
